FROM python:3.9


COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY templates/ templates/
COPY predict.py predict.py
Copy main.py main.py


# Expose the Docker container for the application to run on port 4000
EXPOSE 4000
CMD [ "python3", "main.py" ]
